name: CI

on: [push, pull_request]

jobs:
  validate:
    name: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.0.1']
    env:
      CONFIG: "--enable-tests"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup Haskell
        uses: haskell/actions/setup@v1.2.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.4.0.0'

      - name: Check Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build
        run: cabal build $CONFIG

      - name: Test
        run: |
          cabal test parser-test $CONFIG --test-options="--quickcheck-replay=461077"
          cabal test convert-test $CONFIG
